import { expect, test } from '@playwright/test';
import { enableHealing, healable } from 'ai-healing-sdk';
import type { GeneratedLocatorCandidate, LocatorStrategy } from '../core/healing-types';
import { withHealingPage } from '../core/self-healing';

test.describe('ai-healing-sdk phase 1 API', () => {
  test('enableHealing + healable.click uses locator healing after primary failure', async () => {
    const pageStub = {
      url: () => 'https://example.local/login',
      locator: (value: string) => ({
        kind: value.includes('submit') ? 'healed' : 'broken',
        page: () => pageStub,
        first() {
          return {
            click: async () => {
              if (this.kind === 'broken') throw new Error('element not found');
            },
            count: async () => (this.kind === 'healed' ? 1 : 0),
          };
        },
        click: async function () {
          await this.first().click();
        },
      }),
      getByRole: () => ({
        first() {
          return { count: async () => 0 };
        },
      }),
    } as any;

    enableHealing(pageStub, { healingEnabled: true, persistenceEnabled: false });

    const candidate: GeneratedLocatorCandidate = {
      strategyName: 'autogen-css-1',
      query: { type: 'css', value: 'button[type="submit"]' },
      score: 88,
      reason: 'submit fallback',
    };

    const brokenLocator = {
      page: () => pageStub,
      first() {
        return {
          click: async () => {
            throw new Error('element not found');
          },
        };
      },
    } as any;

    const result = await healable.click(brokenLocator, {
      engineOptions: {
        autoHeal: {
          discoverer: async () => [candidate],
        },
      },
    });

    expect(result.autoHeal?.usedAutoGenerated).toBe(true);
    expect(result.usedStrategy).toBe('autogen-css-1');
  });

  test('core re-exports remain compatible with strategy-based healing', async () => {
    const pageStub = {
      url: () => 'https://example.local/',
      locator: () => ({ first: () => ({ count: async () => 0 }) }),
      getByRole: () => ({ first: () => ({ count: async () => 0 }) }),
    } as any;

    const strategies: LocatorStrategy[] = [
      {
        name: 'works',
        resolve: () => ({ first: async () => 'ok' } as any),
      },
    ];

    const result = await withHealingPage(pageStub, strategies, async (loc: any) => loc.first());
    expect(result.usedStrategy).toBe('works');
  });
});
