import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { expect, test } from '@playwright/test';
import { persistGeneratedLocator } from '../core/auto-heal-persistence';
import { failIfDemoDashboardMetrics } from './demo-dashboard-failures';
import { withHealingPage } from '../core/self-healing';
import type { GeneratedLocatorCandidate, LocatorStrategy } from '../core/healing-types';

test.describe('auto-heal DOM + history behavior', () => {
  test('uses generated fallback candidate after static strategies fail', async () => {
    const pageStub = {
      url: () => 'https://example.local/login',
      locator: (value: string) => ({
        kind: value.includes('email') ? 'auto' : 'other',
        first() {
          return {
            count: async () => (value.includes('email') ? 1 : 0),
          };
        },
      }),
      getByRole: () => ({
        kind: 'role',
        first() {
          return { count: async () => 0 };
        },
      }),
    } as any;

    const staticStrategies: LocatorStrategy[] = [
      {
        name: 'broken-primary',
        resolve: () => ({ kind: 'broken' } as any),
      },
    ];

    const candidate: GeneratedLocatorCandidate = {
      strategyName: 'autogen-css-1',
      query: { type: 'css', value: 'input[type="email"]' },
      score: 80,
      reason: 'email fallback',
    };

    const result = await withHealingPage(
      pageStub,
      staticStrategies,
      async (loc: any) => {
        if (loc.kind === 'broken') throw new Error('primary broke');
        if (loc.kind === 'auto') return 'healed';
        throw new Error('unexpected locator');
      },
      {
        actionType: 'fill',
        autoHeal: {
          enabled: true,
          discoverOnly: true,
          discoverer: async () => [candidate],
        },
      }
    );

    expect(result.value).toBe('healed');
    expect(result.autoHeal?.usedAutoGenerated).toBe(true);
    expect(result.autoHeal?.selectedCandidate?.strategyName).toBe('autogen-css-1');
    expect(result.attempts[0].strategy).toBe('broken-primary');
    expect(result.attempts[1].autogenerated).toBe(true);
    failIfDemoDashboardMetrics();
  });

  test('persists generated locator into target strategy method', async () => {
    const root = mkdtempSync(join(tmpdir(), 'auto-heal-'));
    const targetFile = join(root, 'login.page.ts');
    writeFileSync(
      targetFile,
      [
        'import type { LocatorStrategy } from "../core/healing-types";',
        'class LoginPage {',
        '  private emailStrategies(): LocatorStrategy[] {',
        '    return [',
        '      {',
        '        name: "getByLabel-Email",',
        '        resolve: (p) => p.getByLabel(/email/i),',
        '      },',
        '    ];',
        '  }',
        '}',
      ].join('\n'),
      'utf8'
    );

    const persisted = persistGeneratedLocator({
      target: { filePath: targetFile, methodName: 'emailStrategies' },
      candidate: {
        strategyName: 'autogen-css-1',
        query: { type: 'css', value: 'input[type="email"], input[name*="email" i]' },
        score: 96,
        reason: 'high confidence from DOM+history',
      },
      minConfidence: 80,
      validationPasses: 2,
    });

    expect(persisted.ok).toBe(true);
    const out = readFileSync(targetFile, 'utf8');
    expect(out).toContain("name: 'autogen-css-1'");
    expect(out).toContain("locator('input[type=\"email\"], input[name*=\"email\" i]')");

    rmSync(root, { recursive: true, force: true });
  });
});
