package com.mmohansqaai.aihealing.selenium;

import com.mmohansqaai.aihealing.client.HealingServiceClient;
import com.mmohansqaai.aihealing.model.GeneratedLocatorQuery;
import com.mmohansqaai.aihealing.model.HealingActionType;
import com.mmohansqaai.aihealing.model.HealingAttempt;
import com.mmohansqaai.aihealing.model.HealingRequest;
import com.mmohansqaai.aihealing.model.HealingResponse;
import com.mmohansqaai.aihealing.model.HealingResponseCandidate;
import com.mmohansqaai.aihealing.model.HealingResult;
import com.mmohansqaai.aihealing.util.LocatorFormat;
import java.io.IOException;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public final class Healable {
  private Healable() {}

  public static HealingResult<Void> click(String cssSelector) throws IOException, InterruptedException {
    return click(GeneratedLocatorQuery.css(cssSelector), false, null);
  }

  public static HealingResult<Void> click(GeneratedLocatorQuery query) throws IOException, InterruptedException {
    return click(query, false, null);
  }

  public static HealingResult<Void> click(GeneratedLocatorQuery query, boolean force, Duration timeout)
      throws IOException, InterruptedException {
    return withHealing(HealingActionType.click, query, (driver, q) -> {
      driver.click(q, timeout, force);
      return null;
    });
  }

  public static HealingResult<Void> fill(String cssSelector, String value) throws IOException, InterruptedException {
    return fill(GeneratedLocatorQuery.css(cssSelector), value, null);
  }

  public static HealingResult<Void> fill(GeneratedLocatorQuery query, String value, Duration timeout)
      throws IOException, InterruptedException {
    return withHealing(HealingActionType.fill, query, (driver, q) -> {
      driver.fill(q, value, timeout);
      return null;
    });
  }

  public static HealingResult<Void> expectVisible(String cssSelector) throws IOException, InterruptedException {
    return expectVisible(GeneratedLocatorQuery.css(cssSelector), null);
  }

  public static HealingResult<Void> expectVisible(GeneratedLocatorQuery query, Duration timeout)
      throws IOException, InterruptedException {
    return withHealing(HealingActionType.visible, query, (driver, q) -> {
      if (!driver.isVisible(q, timeout)) {
        throw new IllegalStateException("Locator not visible: " + LocatorFormat.format(q));
      }
      return null;
    });
  }

  @FunctionalInterface
  private interface HealingAction {
    Void run(SeleniumHealingDriver driver, GeneratedLocatorQuery query);
  }

  private static HealingResult<Void> withHealing(
      HealingActionType actionType,
      GeneratedLocatorQuery primary,
      HealingAction action
  ) throws IOException, InterruptedException {
    HealingConfig config = HealingContext.config();
    SeleniumHealingDriver driver = new SeleniumHealingDriver(
        HealingContext.requireDriver(),
        config.timeout
    );
    List<HealingAttempt> attempts = new ArrayList<>();

    try {
      action.run(driver, primary);
      return directSuccess(attempts);
    } catch (RuntimeException primaryError) {
      HealingAttempt attempt = new HealingAttempt();
      attempt.strategy = LocatorFormat.format(primary);
      attempt.ok = false;
      attempt.error = primaryError.getMessage();
      attempt.query = primary;
      attempts.add(attempt);
    }

    if (!config.healingEnabled) {
      throw new IllegalStateException("Healing disabled and primary failed");
    }

    List<HealingResult.GeneratedLocatorCandidate> candidates = resolveCandidates(driver, actionType, attempts, config);
    for (HealingResult.GeneratedLocatorCandidate candidate : candidates) {
      try {
        action.run(driver, candidate.query);
        HealingAttempt ok = new HealingAttempt();
        ok.strategy = candidate.strategyName;
        ok.ok = true;
        ok.autogenerated = true;
        ok.score = candidate.score;
        ok.reason = candidate.reason;
        ok.query = candidate.query;
        attempts.add(ok);

        HealingResult<Void> result = new HealingResult<>();
        result.value = null;
        result.usedStrategy = candidate.strategyName;
        result.attempts = attempts;
        HealingResult.AutoHeal autoHeal = new HealingResult.AutoHeal();
        autoHeal.usedAutoGenerated = true;
        autoHeal.selectedCandidate = candidate;
        autoHeal.candidates = candidates;
        result.autoHeal = autoHeal;
        return result;
      } catch (RuntimeException candidateError) {
        HealingAttempt failed = new HealingAttempt();
        failed.strategy = candidate.strategyName;
        failed.ok = false;
        failed.error = candidateError.getMessage();
        failed.autogenerated = true;
        failed.score = candidate.score;
        failed.reason = candidate.reason;
        failed.query = candidate.query;
        attempts.add(failed);
      }
    }

    String last = attempts.isEmpty() ? "unknown" : attempts.get(attempts.size() - 1).error;
    throw new IllegalStateException("Healing exhausted for " + actionType + ". Last error: " + last);
  }

  private static HealingResult<Void> directSuccess(List<HealingAttempt> attempts) {
    HealingAttempt attempt = new HealingAttempt();
    attempt.strategy = "direct";
    attempt.ok = true;
    attempts.add(attempt);

    HealingResult<Void> result = new HealingResult<>();
    result.value = null;
    result.usedStrategy = "direct";
    result.attempts = attempts;
    return result;
  }

  private static List<HealingResult.GeneratedLocatorCandidate> resolveCandidates(
      SeleniumHealingDriver driver,
      HealingActionType actionType,
      List<HealingAttempt> attempts,
      HealingConfig config
  ) throws IOException, InterruptedException {
    if (config.healingServiceUrl == null || config.healingServiceUrl.isBlank()) {
      return List.of();
    }

    HealingServiceClient client = new HealingServiceClient(config.healingServiceUrl, config.timeout);
    HealingRequest request = new HealingRequest();
    request.framework = config.framework;
    request.action = actionType;
    request.failedLocator = attempts.isEmpty() ? "primary" : attempts.get(attempts.size() - 1).strategy;
    request.error = attempts.isEmpty() ? "primary locator failed" : attempts.get(attempts.size() - 1).error;
    request.url = driver.url();
    request.pageTitle = driver.title();
    request.domSnapshot = driver.captureDomSnapshot(actionType);

    HealingResponse response = client.heal(request);
    if (!response.isHealed() || response.candidates == null || response.candidates.isEmpty()) {
      return List.of();
    }

    List<HealingResult.GeneratedLocatorCandidate> mapped = new ArrayList<>();
    for (HealingResponseCandidate candidate : response.candidates) {
      HealingResult.GeneratedLocatorCandidate item = new HealingResult.GeneratedLocatorCandidate();
      item.strategyName = candidate.strategy;
      item.query = candidate.query;
      item.score = candidate.score;
      item.reason = "[agentic-service] " + candidate.reasoning;
      mapped.add(item);
    }

    mapped.sort(Comparator.comparingInt((HealingResult.GeneratedLocatorCandidate c) -> c.score).reversed());
    return mapped.subList(0, Math.min(config.maxCandidates, mapped.size()));
  }
}
