/** Supported test frameworks (extend via string for custom adapters). */
export type TestFramework = 'playwright' | 'cypress' | 'selenium' | 'webdriverio' | (string & {});

export type HealingActionType = 'click' | 'fill' | 'visible';

export type LocatorSource = {
  filePath?: string;
  methodName?: string;
  actionKey?: string;
};

/** Framework-neutral locator query — adapters map to native APIs. */
export type GeneratedLocatorQuery =
  | { type: 'css'; value: string }
  | { type: 'role'; role: string; name: string };

export type GeneratedLocatorCandidate = {
  strategyName: string;
  query: GeneratedLocatorQuery;
  score: number;
  reason: string;
};

export type HealingAttempt = {
  strategy: string;
  ok: boolean;
  error?: string;
  source?: LocatorSource;
  autogenerated?: boolean;
  score?: number;
  reason?: string;
  query?: GeneratedLocatorQuery;
};

export type HealingResult<T> = {
  value: T;
  usedStrategy: string;
  attempts: HealingAttempt[];
  autoHeal?: {
    usedAutoGenerated: boolean;
    selectedCandidate?: GeneratedLocatorCandidate;
    candidates?: GeneratedLocatorCandidate[];
    persisted?: {
      filePath: string;
      methodName: string;
      strategyName: string;
    };
  };
};

/** Serializable DOM element from an in-page inventory pass (all frameworks). */
export type DomElementSnapshot = {
  tag: string;
  inputType?: string;
  id?: string;
  name?: string;
  testId?: string;
  role?: string;
  ariaLabel?: string;
  placeholder?: string;
  text?: string;
  href?: string;
  disabled: boolean;
};
