import type { TestInfo } from '@playwright/test';
import type { HealingResult } from '../core/healing-types';

/** Plain-text report body for a single healing result (shared by per-step and aggregated attachments). */
export function formatHealingBody(result: HealingResult<unknown>): string {
  const lines = [
    `Used strategy: ${result.usedStrategy}`,
    '',
    'Attempts:',
    ...result.attempts.map((a) => `${a.ok ? '✓' : '✗'} ${a.strategy}${a.error ? ` — ${a.error}` : ''}`),
  ];
  if (result.autoHeal) {
    lines.push('');
    lines.push('Auto-heal:');
    lines.push(`usedAutoGenerated=${result.autoHeal.usedAutoGenerated ? 'true' : 'false'}`);
    if (result.autoHeal.selectedCandidate) {
      lines.push(
        `selected=${result.autoHeal.selectedCandidate.strategyName} score=${result.autoHeal.selectedCandidate.score}`
      );
      lines.push(`reason=${result.autoHeal.selectedCandidate.reason}`);
    }
    if (result.autoHeal.candidates?.length) {
      lines.push('candidates:');
      for (const c of result.autoHeal.candidates) {
        lines.push(`- ${c.strategyName} score=${c.score} query=${JSON.stringify(c.query)} reason=${c.reason}`);
      }
    }
    if (result.autoHeal.persisted) {
      lines.push(
        `persisted=${result.autoHeal.persisted.filePath}#${result.autoHeal.persisted.methodName} (${result.autoHeal.persisted.strategyName})`
      );
    }
  }
  return lines.join('\n');
}

/** Attach healing metadata to the test report (visible in HTML report). */
export function attachHealingSummary(
  testInfo: TestInfo,
  label: string,
  result: HealingResult<unknown>
): Promise<void> {
  return testInfo.attach(`${label}-healing`, {
    body: formatHealingBody(result),
    contentType: 'text/plain',
  });
}

/**
 * Single presentation attachment for live auto-heal demos: exact name `auto-heal-live-proof`
 * (HTML report → Attachments). Aggregates multiple steps with section headers.
 */
export function attachLiveAutoHealProof(
  testInfo: TestInfo,
  sections: { title: string; result: HealingResult<unknown> }[]
): Promise<void> {
  const header = [
    'Auto-heal live demo',
    'AUTO_HEAL_DISCOVER=1 (or autoHeal.enabled in code) enables discovery after static strategies fail.',
    'This demo uses decoy-only strategies so static locators fail once; then auto-heal discovers the live DOM.',
    'AUTO_HEAL_PERSIST is not set for persistence (discover-only is safe for showcases).',
    '',
  ].join('\n');
  const body = sections
    .map((s) => [`=== ${s.title} ===`, formatHealingBody(s.result), ''].join('\n'))
    .join('\n');
  return testInfo.attach('auto-heal-live-proof', {
    body: `${header}\n${body}`,
    contentType: 'text/plain',
  });
}
