import { attachLiveAutoHealProof } from 'ai-healing-sdk';
import { clickHealing } from 'ai-healing-sdk';
import { expect, test } from './fixtures';
import {
  DEMO_PAUSE_MS,
  demoHealingToast,
  ensureCustomerOnProductsPage,
  formatHealedLocator,
  hideHealingModeIndicator,
  miss,
  showHealingModeIndicator,
} from './demo-toast-helpers';

const healingServiceUrl = process.env.HEALING_SERVICE_URL ?? 'http://localhost:3921';

test.describe('Phase 2 — healing-service gateway @healing-service-phase2', () => {
  test.beforeAll(() => {
    process.env.HEALING_SERVICE_URL = healingServiceUrl;
    process.env.AUTO_HEAL_DISCOVER = '1';
    delete process.env.AUTO_HEAL_PERSIST;
  });

  test('add-to-cart recovers via remote healing-service (headed)', async (
    { page, loginPage: login, retailJourney: journey },
    testInfo
  ) => {
    testInfo.setTimeout(180_000);

    await login.goto();
    await login.expectLoaded();
    await Promise.all([
      page.waitForURL((url) => !/\/login\/?$/.test(url.pathname), { timeout: 60_000 }),
      login.loginAsCustomer(),
    ]);
    await ensureCustomerOnProductsPage(page);
    await journey.expectProductsReady();

    await showHealingModeIndicator(page, 'dynamic');
    await demoHealingToast(
      page,
      'dynamic',
      'Phase 2 — healing-service',
      `Remote gateway: ${healingServiceUrl}\n\nFlow: broken locator → SDK POST /heal → locator recovery agent → retry on browser.`,
      'info'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    const brokenLocator = 'button[data-demo-miss-service="1"]';
    await demoHealingToast(
      page,
      'dynamic',
      'Sending HealingRequest to service',
      `Broken locator: ${brokenLocator}\nWatch the service recover Add to cart via POST /heal.`,
      'warn',
      10_000
    );
    await page.waitForTimeout(2_000);

    const addToCart = await clickHealing(page, [miss('service-miss-demo', brokenLocator)], {
      actionType: 'click',
      autoHeal: {
        enabled: true,
        discoverOnly: true,
        minConfidence: 70,
      },
      timeoutPerStrategyMs: 12_000,
    });

    expect(addToCart.autoHeal?.usedAutoGenerated).toBe(true);
    const selected = addToCart.autoHeal?.selectedCandidate;
    expect(selected).toBeTruthy();

    const healedLocator = formatHealedLocator(selected?.query, addToCart.usedStrategy);
    await demoHealingToast(
      page,
      'dynamic',
      'HealingResponse received',
      `Service strategy: ${selected?.strategyName}\nScore: ${selected?.score}\nLocator: ${healedLocator}`,
      'success',
      12_000
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    await attachLiveAutoHealProof(testInfo, [
      { title: 'Phase 2 healing-service /heal', result: addToCart },
    ]);
    await hideHealingModeIndicator(page);
  });
});
