import { attachLiveAutoHealProof } from 'ai-healing-sdk';
import { clickHealing } from 'ai-healing-sdk';
import { expect, test } from './fixtures';
import {
  DEMO_PAUSE_MS,
  demoHealingToast,
  ensureCustomerOnProductsPage,
  formatHealedLocator,
  hideHealingModeIndicator,
  miss,
  showHealingModeIndicator,
} from './demo-toast-helpers';

const healingServiceUrl = process.env.HEALING_SERVICE_URL ?? 'http://localhost:3921';

test.describe('Phase 3 — locator-agent @locator-agent-phase3', () => {
  test.beforeAll(() => {
    process.env.HEALING_SERVICE_URL = healingServiceUrl;
    process.env.AUTO_HEAL_DISCOVER = '1';
    delete process.env.AUTO_HEAL_PERSIST;
  });

  test('add-to-cart recovers via locator-agent with confidence scoring (headed)', async (
    { page, loginPage: login, retailJourney: journey },
    testInfo
  ) => {
    testInfo.setTimeout(180_000);

    await login.goto();
    await login.expectLoaded();
    await Promise.all([
      page.waitForURL((url) => !/\/login\/?$/.test(url.pathname), { timeout: 60_000 }),
      login.loginAsCustomer(),
    ]);
    await ensureCustomerOnProductsPage(page);
    await journey.expectProductsReady();

    await showHealingModeIndicator(page, 'dynamic');
    await demoHealingToast(
      page,
      'dynamic',
      'Phase 3 — locator-agent',
      `Service: ${healingServiceUrl}\n\nStrategies: semantic_matching, dom_neighborhood, attribute_similarity, accessibility_recovery, historical_learning\n\nWatch confidence scoring on healed locator.`,
      'info'
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    const brokenLocator = 'button[data-demo-miss-locator-agent="1"]';
    await demoHealingToast(
      page,
      'dynamic',
      'Broken locator → locator-agent',
      `Broken: ${brokenLocator}\nAgent modules score and rank recovery candidates.`,
      'warn',
      10_000
    );
    await page.waitForTimeout(2_000);

    const addToCart = await clickHealing(page, [miss('locator-agent-miss-demo', brokenLocator)], {
      actionType: 'click',
      autoHeal: { enabled: true, discoverOnly: true, minConfidence: 70 },
      timeoutPerStrategyMs: 12_000,
    });

    expect(addToCart.autoHeal?.usedAutoGenerated).toBe(true);
    const selected = addToCart.autoHeal?.selectedCandidate;
    expect(selected).toBeTruthy();
    expect(selected!.score).toBeGreaterThan(0);

    const healedLocator = formatHealedLocator(selected?.query, addToCart.usedStrategy);
    const confidence = Math.min(1, selected!.score / 100).toFixed(2);

    await demoHealingToast(
      page,
      'dynamic',
      'Locator-agent healed',
      `Strategy: ${selected?.strategyName}\nScore: ${selected?.score}\nConfidence: ${confidence}\nLocator: ${healedLocator}`,
      'success',
      12_000
    );
    await page.waitForTimeout(DEMO_PAUSE_MS);

    await attachLiveAutoHealProof(testInfo, [
      { title: 'Phase 3 locator-agent recovery', result: addToCart },
    ]);
    await hideHealingModeIndicator(page);
  });
});
