package com.mmohansqaai.aihealing.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.ArrayList;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class HealingResult<T> {
  public T value;
  public String usedStrategy;
  public List<HealingAttempt> attempts = new ArrayList<>();
  public AutoHeal autoHeal;

  @JsonInclude(JsonInclude.Include.NON_NULL)
  public static class AutoHeal {
    public boolean usedAutoGenerated;
    public GeneratedLocatorCandidate selectedCandidate;
    public List<GeneratedLocatorCandidate> candidates;
  }

  @JsonInclude(JsonInclude.Include.NON_NULL)
  public static class GeneratedLocatorCandidate {
    public String strategyName;
    public GeneratedLocatorQuery query;
    public int score;
    public String reason;
  }
}
