package com.mmohansqaai.aihealing.model;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class HealingAttempt {
  public String strategy;
  public boolean ok;
  public String error;
  public Boolean autogenerated;
  public Integer score;
  public String reason;
  public GeneratedLocatorQuery query;
}
