import type { Locator, Page } from '@playwright/test';
import type { DiscoveryStrategyName } from '../core/discovery/compose-discoverers';
import { generatedQueryKey, generatedQueryToLocatorFactory } from '../core/locator-query';
import { recordHistoryOutcome } from '../core/history';
import { persistGeneratedLocator } from '../core/persistence';
import type {
  GeneratedLocatorCandidate,
  HealingAttempt,
  HealingResult,
  LocatorStrategy,
  HealingActionType,
} from '../core/healing-types';
import { formatExhaustedStrategiesError, recordStrategyFailure } from '../interceptors/failure-handler';
import type { DiscovererFn } from '../transport/local-transport';
import { resolveDefaultDiscoverer } from '../transport/resolve-discoverer';
import { envTruthy } from '../utils/env';
import type { HealingAgentMode } from '../utils/config';
import { runAgenticHealingLoop } from '../agent/agent-loop';

const DEFAULT_PER_STRATEGY_MS = 5_000;
const DEFAULT_MIN_CONFIDENCE = 70;

type AutoHealPersistTarget = {
  filePath: string;
  methodName: string;
};

export type AutoHealOptions = {
  enabled?: boolean;
  agentMode?: HealingAgentMode;
  maxAgentIterations?: number;
  healingServiceUrl?: string;
  discoverOnly?: boolean;
  minConfidence?: number;
  persistTarget?: AutoHealPersistTarget;
  validationPasses?: number;
  discoveryStrategies?: DiscoveryStrategyName[];
  discoverer?: DiscovererFn;
};

export type HealingOptions = {
  timeoutPerStrategyMs?: number;
  actionType?: HealingActionType;
  autoHeal?: AutoHealOptions;
  telemetryEnabled?: boolean;
  verboseLogs?: boolean;
};

function resolveAgentMode(options?: HealingOptions): HealingAgentMode {
  const fromOptions = options?.autoHeal?.agentMode;
  if (fromOptions) return fromOptions;
  const fromEnv = (process.env.HEALING_AGENT_MODE ?? 'agentic').toLowerCase();
  if (fromEnv === 'off' || fromEnv === 'legacy') return fromEnv;
  return 'agentic';
}

function resolveAutoHealConfig(options?: HealingOptions): AutoHealOptions {
  const auto = options?.autoHeal ?? {};
  const enabled = auto.enabled ?? envTruthy(process.env.AUTO_HEAL_DISCOVER);
  const discoverOnly = auto.discoverOnly ?? !envTruthy(process.env.AUTO_HEAL_PERSIST);
  const minConfidence = auto.minConfidence ?? Number(process.env.AUTO_HEAL_MIN_CONFIDENCE || DEFAULT_MIN_CONFIDENCE);
  const validationPasses = auto.validationPasses ?? 2;
  const agentMode = resolveAgentMode(options);
  const maxAgentIterations =
    auto.maxAgentIterations ?? Number(process.env.HEALING_AGENT_MAX_ITERATIONS || 3);
  return {
    ...auto,
    enabled,
    agentMode,
    maxAgentIterations,
    discoverOnly,
    minConfidence: Number.isFinite(minConfidence) ? minConfidence : DEFAULT_MIN_CONFIDENCE,
    validationPasses,
  };
}

async function runLegacyDiscoveryLoop<T>(
  page: Page,
  strategies: LocatorStrategy[],
  action: (locator: Locator) => Promise<T>,
  attempts: HealingAttempt[],
  actionType: HealingActionType,
  autoConfig: AutoHealOptions,
  lastError: unknown
): Promise<HealingResult<T>> {
  const discover =
    autoConfig.discoverer ??
    resolveDefaultDiscoverer({
      discoveryStrategies: autoConfig.discoveryStrategies,
    });
  const generated = await discover({ page, actionType, attempts });
  const candidates: GeneratedLocatorCandidate[] = [];
  for (const c of generated) {
    const bonus = await scoreCandidateViability(page, c);
    if (bonus < -100) continue;
    candidates.push({ ...c, score: c.score + bonus });
  }
  candidates.sort((a, b) => b.score - a.score);

  for (const candidate of candidates) {
    const locator = generatedQueryToLocatorFactory(candidate.query)(page);
    try {
      const value = await action(locator);
      attempts.push({
        strategy: candidate.strategyName,
        ok: true,
        autogenerated: true,
        score: candidate.score,
        reason: candidate.reason,
        query: candidate.query,
      });
      recordHistoryOutcome(page.url(), actionType, generatedQueryKey(candidate.query), true);

      const result: HealingResult<T> = {
        value,
        usedStrategy: candidate.strategyName,
        attempts,
        autoHeal: {
          usedAutoGenerated: true,
          selectedCandidate: candidate,
          candidates,
        },
      };

      const canPersist =
        !autoConfig.discoverOnly &&
        Boolean(
          autoConfig.persistTarget ||
            attempts.find((a) => a.source?.filePath && a.source?.methodName)?.source
        ) &&
        candidate.score >= (autoConfig.minConfidence ?? DEFAULT_MIN_CONFIDENCE);
      const inferredTarget = attempts.find((a) => a.source?.filePath && a.source?.methodName)?.source;
      if (canPersist && (autoConfig.persistTarget || inferredTarget)) {
        const persisted = persistGeneratedLocator({
          target:
            autoConfig.persistTarget ??
            ({
              filePath: inferredTarget!.filePath!,
              methodName: inferredTarget!.methodName!,
            }),
          candidate,
          minConfidence: autoConfig.minConfidence ?? DEFAULT_MIN_CONFIDENCE,
          validationPasses: autoConfig.validationPasses ?? 2,
        });
        if (persisted.ok) {
          result.autoHeal = {
            usedAutoGenerated: true,
            selectedCandidate: candidate,
            candidates,
            persisted: {
              filePath: persisted.filePath,
              methodName: persisted.methodName,
              strategyName: persisted.strategyName,
            },
          };
        }
      }
      return result;
    } catch (e) {
      lastError = e;
      attempts.push({
        strategy: candidate.strategyName,
        ok: false,
        error: e instanceof Error ? e.message : String(e),
        autogenerated: true,
        score: candidate.score,
        reason: candidate.reason,
        query: candidate.query,
      });
      recordHistoryOutcome(page.url(), actionType, generatedQueryKey(candidate.query), false);
    }
  }

  throw formatExhaustedStrategiesError(strategies.length, attempts, lastError);
}

async function scoreCandidateViability(page: Page, candidate: GeneratedLocatorCandidate): Promise<number> {
  try {
    const loc = generatedQueryToLocatorFactory(candidate.query)(page).first();
    const count = await loc.count();
    if (count < 1) return -1000;
    return count === 1 ? 10 : Math.max(0, 6 - count);
  } catch {
    return -1000;
  }
}

/**
 * Runs an action against locators from each strategy until one succeeds.
 * Order matters: stable selectors first, fallbacks after.
 */
export async function withHealingPage<T>(
  page: Page,
  strategies: LocatorStrategy[],
  action: (locator: Locator) => Promise<T>,
  options?: HealingOptions
): Promise<HealingResult<T>> {
  const attempts: HealingAttempt[] = [];
  let lastError: unknown;
  const actionType: HealingActionType = options?.actionType ?? 'visible';
  const autoConfig = resolveAutoHealConfig(options);

  for (const s of strategies) {
    const locator = s.resolve(page);
    try {
      const value = await action(locator);
      attempts.push({ strategy: s.name, ok: true, source: s.source });
      return { value, usedStrategy: s.name, attempts };
    } catch (e) {
      lastError = e;
      recordStrategyFailure(attempts, { strategyName: s.name, error: e, source: s.source });
    }
  }

  if (autoConfig.enabled) {
    if (autoConfig.agentMode === 'agentic') {
      return runAgenticHealingLoop(page, strategies, action, attempts, actionType, {
        maxIterations: autoConfig.maxAgentIterations,
        minConfidence: autoConfig.minConfidence,
        discoverOnly: autoConfig.discoverOnly,
        validationPasses: autoConfig.validationPasses,
        discoveryStrategies: autoConfig.discoveryStrategies,
        discoverer: autoConfig.discoverer,
        persistTarget: autoConfig.persistTarget,
        healingServiceUrl: autoConfig.healingServiceUrl,
        telemetryEnabled: options?.telemetryEnabled,
        verboseLogs: options?.verboseLogs,
      });
    }

    return runLegacyDiscoveryLoop(page, strategies, action, attempts, actionType, autoConfig, lastError);
  }

  throw formatExhaustedStrategiesError(strategies.length, attempts, lastError);
}

export async function clickHealing(
  page: Page,
  strategies: LocatorStrategy[],
  options?: HealingOptions & { force?: boolean }
): Promise<HealingResult<void>> {
  const timeout = options?.timeoutPerStrategyMs ?? DEFAULT_PER_STRATEGY_MS;
  return withHealingPage(
    page,
    strategies,
    async (loc) => {
      await loc.first().click({ timeout, force: options?.force });
    },
    { ...options, actionType: 'click' }
  );
}

export async function fillHealing(
  page: Page,
  strategies: LocatorStrategy[],
  value: string,
  options?: HealingOptions
): Promise<HealingResult<void>> {
  const timeout = options?.timeoutPerStrategyMs ?? DEFAULT_PER_STRATEGY_MS;
  return withHealingPage(
    page,
    strategies,
    async (loc) => {
      await loc.first().fill(value, { timeout });
    },
    { ...options, actionType: 'fill' }
  );
}

export async function expectVisibleHealing(
  page: Page,
  strategies: LocatorStrategy[],
  options?: HealingOptions
): Promise<HealingResult<void>> {
  const timeout = options?.timeoutPerStrategyMs ?? DEFAULT_PER_STRATEGY_MS;
  return withHealingPage(
    page,
    strategies,
    async (loc) => {
      await loc.first().waitFor({ state: 'visible', timeout });
    },
    { ...options, actionType: 'visible' }
  );
}
