import type { Locator, Page } from '@playwright/test';
import type { LocatorStrategy, HealingResult } from '../core/healing-types';
import {
  clickHealing,
  expectVisibleHealing,
  fillHealing,
  type HealingOptions,
} from '../retry/retry-orchestrator';
import { emitTelemetry } from '../telemetry/telemetry';
import { sdkConfigToEngineOptions } from '../utils/config';
import { isHealingEnabledForPage, resolvePageHealingConfig } from './page-registry';

export type HealableClickOptions = {
  force?: boolean;
  timeoutPerStrategyMs?: number;
  engineOptions?: Partial<HealingOptions>;
};

export type HealableFillOptions = {
  timeoutPerStrategyMs?: number;
  engineOptions?: Partial<HealingOptions>;
};

function primaryLocatorStrategy(locator: Locator, name = 'primary-locator'): LocatorStrategy[] {
  return [
    {
      name,
      resolve: () => locator,
    },
  ];
}

function resolveEngineOptions(
  page: Page,
  actionType: 'click' | 'fill' | 'visible',
  overrides?: Partial<HealingOptions>
): HealingOptions {
  const config = resolvePageHealingConfig(page);
  const base = sdkConfigToEngineOptions(config, { actionType });
  return {
    ...base,
    ...overrides,
    autoHeal: {
      ...base.autoHeal,
      ...overrides?.autoHeal,
    },
  };
}

async function runWithTelemetry<T>(
  page: Page,
  action: string,
  run: () => Promise<HealingResult<T>>
): Promise<HealingResult<T>> {
  const config = resolvePageHealingConfig(page);
  emitTelemetry({ type: 'healing.start', action, url: page.url() }, config.telemetryEnabled, config.verboseLogs);
  try {
    const result = await run();
    if (result.autoHeal?.usedAutoGenerated) {
      emitTelemetry(
        {
          type: 'healing.auto_heal_success',
          strategy: result.usedStrategy,
          score: result.autoHeal.selectedCandidate?.score,
        },
        config.telemetryEnabled,
        config.verboseLogs
      );
    } else {
      emitTelemetry(
        { type: 'healing.static_success', strategy: result.usedStrategy },
        config.telemetryEnabled,
        config.verboseLogs
      );
    }
    emitTelemetry(
      { type: 'healing.complete', result: result as HealingResult<unknown> },
      config.telemetryEnabled,
      config.verboseLogs
    );
    return result;
  } catch (error) {
    emitTelemetry({ type: 'healing.failure', attempts: 0 }, config.telemetryEnabled, config.verboseLogs);
    throw error;
  }
}

/**
 * Healable action wrappers — try the primary locator, then run locator healing on failure.
 *
 * @example
 * ```ts
 * enableHealing(page);
 * await healable.click(page.locator('#login'));
 * await healable.fill(page.locator('input[name="email"]'), 'user@demo.com');
 * ```
 */
export const healable = {
  async click(locator: Locator, options?: HealableClickOptions): Promise<HealingResult<void>> {
    const page = locator.page();
    if (!isHealingEnabledForPage(page)) {
      await locator.click({ force: options?.force, timeout: options?.timeoutPerStrategyMs });
      return {
        value: undefined,
        usedStrategy: 'direct',
        attempts: [{ strategy: 'direct', ok: true }],
      };
    }

    return runWithTelemetry(page, 'click', () =>
      clickHealing(page, primaryLocatorStrategy(locator), {
        ...resolveEngineOptions(page, 'click', options?.engineOptions),
        force: options?.force,
        timeoutPerStrategyMs: options?.timeoutPerStrategyMs,
      })
    );
  },

  async fill(locator: Locator, value: string, options?: HealableFillOptions): Promise<HealingResult<void>> {
    const page = locator.page();
    if (!isHealingEnabledForPage(page)) {
      await locator.fill(value, { timeout: options?.timeoutPerStrategyMs });
      return {
        value: undefined,
        usedStrategy: 'direct',
        attempts: [{ strategy: 'direct', ok: true }],
      };
    }

    return runWithTelemetry(page, 'fill', () =>
      fillHealing(page, primaryLocatorStrategy(locator), value, {
        ...resolveEngineOptions(page, 'fill', options?.engineOptions),
        timeoutPerStrategyMs: options?.timeoutPerStrategyMs,
      })
    );
  },

  async expectVisible(locator: Locator, options?: HealableFillOptions): Promise<HealingResult<void>> {
    const page = locator.page();
    if (!isHealingEnabledForPage(page)) {
      await locator.waitFor({ state: 'visible', timeout: options?.timeoutPerStrategyMs });
      return {
        value: undefined,
        usedStrategy: 'direct',
        attempts: [{ strategy: 'direct', ok: true }],
      };
    }

    return runWithTelemetry(page, 'visible', () =>
      expectVisibleHealing(page, primaryLocatorStrategy(locator), {
        ...resolveEngineOptions(page, 'visible', options?.engineOptions),
        timeoutPerStrategyMs: options?.timeoutPerStrategyMs,
      })
    );
  },
};

export type HealableApi = typeof healable;
